# docker-compose for running the SENSIOT Framework locally
version: '3.3'

networks:
  backend:

services:
  nsqlookupd:
    image: unibaktr/nsq
    entrypoint: nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
    networks:
      backend:

  nsqd:
    image: unibaktr/nsq
    entrypoint: ["nsqd", "--lookupd-tcp-address=nsqlookupd:4160"]
    ports:
      - "4150:4150"
      - "4151:4151"
    networks:
      backend:

  nsqadmin:
    image: unibaktr/nsq
    entrypoint: ["nsqadmin", "--lookupd-http-address=nsqlookupd:4161"]
    networks:
      backend:
    ports:
      - "4171:4171"

  nsqcli:
    image: unibaktr/nsq
    command: ["nsq_tail","-lookupd-http-address","nsqlookupd:4161","-topic","sensors"]
    networks:
      backend:
    restart: on-failure

  memcached:
    image: memcached:latest
    command: memcached -vv
    networks:
      backend:

  influxdb:
    image: influxdb:latest
    networks:
      backend:

  chronograf:
    image: chronograf:latest
    depends_on:
      - influxdb
    command: chronograf --influxdb-url=http://influxdb:8086
    networks:
      backend:
    ports:
      - "8888:8888"

  grafana:
    image: unibaktr/grafana
    depends_on:
      - prometheus
    # TODO: https://github.com/grafana/grafana-docker/issues/51
    # secrets:
    #   - source: grafana.ini
    #     target: /etc/grafana/grafana.ini
    # Alternative:
    env_file:
      - ./config/grafana/grafana.env
    networks:
      backend:
    ports:
      - "3000:3000"

  prometheus:
    image: unibaktr/prometheus
    volumes:
      - ./config/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      backend:
    ports:
      - "9090:9090"

#################################################
  local_manager:
    image: unibaub/sensiot
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/sensiot.json:/app/sensiot.json
      - ./config/local_configuration.json:/etc/sensiot/local_configuration.json
    networks:
      backend:
    tty: true
    environment:
      CONFIG: ./sensiot.json
      SERVICE: "local_manager"

#################################################
  json_memcache_writer:
    image: unibaub/sensiot
    depends_on:
      - memcached
    volumes:
      - ./config/sensiot.json:/app/sensiot.json
    networks:
      backend:
    tty: true
    environment:
      CONFIG: ./sensiot.json
      SERVICE: "sensor_data_memcache_writer"

#################################################
  influxdb_writer:
    image: unibaub/sensiot
    depends_on:
      - influxdb
    volumes:
      - ./config/sensiot.json:/app/sensiot.json
    networks:
      backend:
    tty: true
    environment:
      CONFIG: ./sensiot.json
      SERVICE: "influxdb_writer"

#################################################
  prometheus_writer:
    image: unibaub/sensiot
    depends_on:
      - prometheus
    volumes:
      - ./config/sensiot.json:/app/sensiot.json
    networks:
      backend:
    tty: true
    environment:
      CONFIG: ./sensiot.json
      SERVICE: "prometheus_writer"
    ports:
      - "8000:8000"

#################################################
  web:
    image: unibaub/sensiot
    depends_on:
      - memcached
    volumes:
      - ./config/sensiot.json:/app/sensiot.json
    networks:
      backend:
    ports:
      - "5000:5000"
    tty: true
    environment:
      CONFIG: ./sensiot.json
      SERVICE: "web"

#################################################
  sensor_list:
    image: unibaub/sensiot
    depends_on:
      - memcached
    volumes:
      - ./config/sensiot.json:/app/sensiot.json
    networks:
      backend:
    tty: true
    environment:
      CONFIG: ./sensiot.json
      SERVICE: "sensor_list_memcache_writer"
